name: 'Code review'

on:
  pull_request:
  pull_request_review_comment:
    types: [created]


permissions:
  contents: read
  pull-requests: write

jobs:
  review-action:
    runs-on: gha-runner-scale-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ' ' # Not needed for ollama
        with:
          openai_base_url: 'https://ollama.hnatekmar.xyz/v1'
          openai_heavy_model: 'qwen2.5-coder:32b-instruct-q4_1'
          openai_light_model: 'qwen2.5-coder:7b'
          debug: false
          review_simple_changes: true
          review_comment_lgtm: false