name: 'Code review'

on:
  pull_request:


permissions:
  contents: read
  pull-requests: write

jobs:
  test-windows:
    runs-on: windows-dind
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
          check-latest: 'true'
      - run: go run main.go
  test-linux:
    runs-on: gha-runner-scale-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
          check-latest: 'true'
      - run: go run main.go

  test-osx:
    runs-on: macOS
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
          check-latest: 'true'
      - run: go run main.go